### ISSUE TITLE
Upload UML Use Case Diagrams

### ISSUE THREAD

**Issue by archit120** [archit120/JEDI4_CRSFlipkartProject-Group4#1]
Create three different UML diagrams based on the three different primary actors - students, professors, registrar.

Place your file in `UMLArtifacts/UseCaseDiagrams/` with naming like `StudentUseCase.png` 

 - Students - @shravya-R
 - Professors - @LunaticBoxer75
 - Registrar - @krsnaman

**Comment by archit120** [comment]
Reference image - ![WhatsApp Image 2021-06-08 at 16 49 26](https://user-images.githubusercontent.com/3856626/121178793-8783e500-c87c-11eb-8528-2e59f5b80381.jpeg)

**Comment by krsnaman** [comment]
![RegistrarUseCase](https://user-images.githubusercontent.com/78996705/121189957-37ab1b00-c888-11eb-983e-7833ab7fd5ab.png)

**Comment by krsnaman** [comment]
RegistrarUseCase; the actor "Actor" is Registrar.

**Comment by krsnaman** [comment]
RegistrarUseCase
![RegistrarUseCase](https://user-images.githubusercontent.com/78996705/121190757-fb2bef00-c888-11eb-821b-7831dcc8f1e7.png)

**Comment by archit120** [comment]
Reopening because of changes in diagram
